LEAFS = amr \
       bv \
       celp \
       codec2 \
       g723 \
       g729 \
       gsm \
       gsmer \
       gsmhr \
       ilbc \
       lpc \
       lpc10 \
       melp \
       melpe \
       opus \
       silk \
       speex

include ../Makefile-common.inc
include ../Makefile-spine.inc

